### ISSUE TITLE
Webapp broken, behind Nginx with SSL.

### ISSUE THREAD

**Issue by Vorlif** [dnote/dnote#443]
## Environment

* project (cli, server, browser-extension): server
* version: `dnote-server-1.0.1`
* operating system: Linux / Debian

## Description
I have set up dnote on a server. The functionality of the client is fully given. The webapp also works when I access it via IP:Port. 

I also set up Nginx with SSL as reverse proxy. When I try to open the dnote webapp via the domain (Nginx) the login page is displayed. Unfortunately after logging in only a loading screen appears and the app hangs.

My configuration:
Assuming I use the subdomain dnote.example.com. 

Dnote
```
GO_ENV=PRODUCTION
OnPremise=true
WebURL=https://dnote.example.com
...
```

Nginx
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name dnote.example.com www.dnote.example.com;

    # ... ssl config
    
    location / {
         proxy_set_header X-Real-IP $remote_addr;
	 proxy_set_header X-Forwarded-For $remote_addr;
	 proxy_set_header Host $host;
	 proxy_pass http://127.0.0.1:3000;
    }
}

```

![Screenshot_20200413_094954](https://user-images.githubusercontent.com/4333770/79103151-630da500-7d6c-11ea-8c34-2ebc1c1476c3.jpeg)

![Screenshot_20200413_095314](https://user-images.githubusercontent.com/4333770/79103454-e202dd80-7d6c-11ea-9885-05f202aa803c.jpeg)

## Steps to reproduce
If necessary I can give the developers limited access to the server.

**Comment by sungwoncho** [comment]
Hi @Vorlif, I am sorry to hear about the issue. Thanks for taking time to prepare screenshots and details. :+1: 

It seems like the issue is:

* After you create an account, the app is stuck at the loading screen.
* The app would not log in any user.

Honestly I am a bit out of idea. Below is an Nginx config that has been working for me on Ubuntu 18 running nginx/1.16.1. Could you try something similar?

```nginx
server {
    listen 80;
    server_name  dnote.example.com;

    # Redirect non-https traffic to https
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name  dnote.example.com;

    ssl_certificate ...
    ssl_certificate_key ...
    ssl_trusted_certificate ...

    location / {
        proxy_pass          http://localhost:3000;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_max_temp_file_size 0;
    }
}
```

```yaml
version: "3"
 
services: 
  # postgres
  # ...

  # dnote
  dnote: 
    image: dnote/dnote 
    environment: 
      GO_ENV: PRODUCTION 
      DBSkipSSL: "true" 
      DBHost: postgres 
      DBPort: 5432 
      DBName: # ... 
      DBUser: # ... 
      DBPassword: # ... 
      OnPremise: "true" 
      WebURL: http://dnote.example.com 
      SmtpHost: # ...
      SmtpPort: 587 
      SmtpUsername: # ... 
      SmtpPassword: # ...
      DisableRegistration: "false" 
    ports: 
      - 3000:3000 
    depends_on: 
      - postgres 
    restart: always 
```
