### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by sungwoncho** [dnote/dnote#467]
* **Please describe the feature you would like to have.**
I'd like to install Dnote server on arm64 machine using docker

* **What alternatives have you considered?**
None

* **Any additional context**
How can we support multi platform docker build?

**Comment by sanatv2s** [comment]
An arm64 docker image for something like RaspberryPi would actually be great idea. Where can I find the Dockerfile for the Dnote? Maybe I can try it on my raspberrypi

**Comment by deepanchal** [comment]
I found this dnote build on dockerhub: https://hub.docker.com/r/maaroen/dnote-arm64

This is working on my RPi 4 8Gb:

```yaml
version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dnote
      POSTGRES_PASSWORD: dnote
      POSTGRES_DB: dnote
    volumes:
      - ./dnote_data:/var/lib/postgresql/data
    restart: always

  dnote:
    # image: dnote/dnote:latest
    image: maaroen/dnote-arm64
    environment:
      GO_ENV: PRODUCTION
      DBSkipSSL: "true"
      DBHost: postgres
      DBPort: 5432
      DBName: dnote
      DBUser: dnote
      DBPassword: dnote
      WebURL: localhost:3000
      OnPremises: "true"
      SmtpHost:
      SmtpPort:
      SmtpUsername:
      SmtpPassword:
      DisableRegistration: "false"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
 ```
